### PR TITLE
vpp-base: fixup to point to the current master

### PR DESCRIPTION
**Pull request by ivan4th**
Includes trajectory tracing for debug images and gdbserver in the dev image

### CODE REVIEW

**Review by sergeymatov — APPROVED** [review]

**Comment by mitmitmitm** [comment]
> -VPP_IMAGE_BASE=registry.cennso.com/upg/vpp-base:22.02-rc1-d7dec2ebd
> +VPP_IMAGE_BASE=registry.cennso.com/upg/vpp-base:22.02-rc1-b604c8406

May I ask if these vpp commits are available in any publicly clone-able
vpp git repository?

**Comment by mitmitmitm** [comment]
> -VPP_IMAGE_BASE=registry.cennso.com/upg/vpp-base:22.02-rc1-d7dec2ebd
> +VPP_IMAGE_BASE=registry.cennso.com/upg/vpp-base:22.02-rc1-b604c8406

May I ask if these vpp commits are available in any publicly clone-able
vpp git repository?

**Comment by mgumz** [comment]
@mitmitmitm: these images won't be public available as of now. if you need to maintain your clone of our work, then you also have to provide the base image.

**Comment by mitmitmitm** [comment]
> @mitmitmitm: these images won't be public available as of now. if you need to maintain your clone of our work, then you also have to provide the base image.

OK, as I understand, your vpp /images/ aren't available publicly. Is
this true for your vpp /source code/ as well?

My current understanding:

commit a1b70b15d83145dd2fb2755f6b2b593a6a78f293
Author: Ivan Shvedunov ***@***.***>
Date:   Thu Nov 25 11:57:03 2021 +0300

    Build UPG as an external VPP plugin

Prior to this commit, the upg-vpp repository contained patches for vpp.
One could apply them to the vpp source code and build it to get the
required vpp binary for upg-vpp.

This commit however removed all these patches and made the |vpp.spec|
file point to a vpp-base image, which I presume is built from some sort
of vpp fork you maintain. That is, the original vpp source code + some
of your modifications not unlike the patches you used to have in upg-vpp
repository.

My questions: is my assumption correct? Does your vpp fork has its
source code publicly available? If not, is your out-of-tree upf plugin
compatible with vanilla vpp?

**Comment by mgumz** [comment]
> If not, is your out-of-tree upf plugin compatible with vanilla vpp?

It is.

**Comment by mitmitmitm** [comment]
Ok, thanks.

**Comment by mitmitmitm** [comment]
> -VPP_IMAGE_BASE=registry.cennso.com/upg/vpp-base:22.02-rc1-d7dec2ebd
> +VPP_IMAGE_BASE=registry.cennso.com/upg/vpp-base:22.02-rc1-b604c8406

May I ask if these vpp commits are available in any publicly clone-able
vpp git repository?

**Comment by mitmitmitm** [comment]
Mathias Gumz ***@***.***> writes:

> It is.

OK, thanks.

**Pull request merged**
